### ISSUE TITLE
Data Science deployment delete - Cloud Build run failed

### ISSUE THREAD

**Issue by JasperW01** [GoogleCloudPlatform/rad-lab#143]
**Describe the bug**
The Cloud Build run in the RADLab UI failed when delete Data Science deployment from the RADLab UI

**To Reproduce**
1. Log onto RADLab UI
2. Go to deploy to deploy the Data Science module
3. The module is deployed successfully
4. Go to the deployment tab to select the successful deployment
5. Click delete button
6. Even though all the resources in the new Data Science GCP Project have been destroyed successfully. But the Cloud Build run in the RADLab UI's GCP Project shows as failed and also the Data Science GCP Project is left over.  

**Expected behavior**
The Cloud Build run in RADLab UI project should be shown as successful and also the Data Science module's GCP Project should be deleted. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version [Any](<img width="1732" alt="Screenshot 2023-03-26 at 10 58 56 am" src="https://user-images.githubusercontent.com/14971090/227748008-d97800f2-4ef2-4321-a45b-ec2cbf250496.png">)

**Additional context**

**Logs**
Any relevant logs that you can provide. Please remove any identifying information.

**Labels**
Please add a label that identifies what component(s) this issue applies to.

**Comment by guptamukul-google** [comment]
@JasperW01 We have worked internally and this issue should be fixed now and is already merged to main. Please re-open the issue if you see the same issue again.
