### ISSUE TITLE
Unprotected endpoints?

### ISSUE THREAD

**Issue by fellnerse** [GoogleCloudPlatform/rad-lab#153]
I setup radlab and am experimenting with it. So far it looks really great, thanks for open sourcing this. But I'm wondering regarding the default protection of the app engine endpoints. It looks like they are not protected:
https://github.com/GoogleCloudPlatform/rad-lab/blob/327de9c639dbc1e4a81aa5051db9a9ba9db5a882/radlab-ui/webapp/src/pages/api/settings.ts#L27

Am I missing something? If not, why are you not using the firebase auth? Because now it looks like the frontend is doing all "protection".

Thanks in advance!

**Comment by acolver** [comment]
Thanks for raising the issue. We could leverage Firebase Auth and NextJS middleware to authenticate and also authorize (admin vs user).

In the mean time you may be able to secure with Identity Aware Proxy: https://cloud.google.com/beyondcorp-enterprise/docs/securing-app-engine

**Comment by fellnerse** [comment]
Thank you for your fast response. 
that’s also what I thought, and already tried, but it looks like that firebase admin is not available in the edge environment the next.js middleware is running in. See https://www.reddit.com/r/Firebase/comments/sbhg4b/comment/hu0p5x7/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button

so I was wondering if you are interested in working together on this, we really need our BE to be secured, before we can actually use RAD Lab

**Comment by acolver** [comment]
https://github.com/GoogleCloudPlatform/rad-lab/pull/158

**Comment by acolver** [comment]
This issue has been fixed by https://github.com/GoogleCloudPlatform/rad-lab/pull/158
