### ISSUE TITLE
 time range of budgets - budget.tf

### ISSUE THREAD

**Issue by speralta-burwood** [GoogleCloudPlatform/rad-lab#167]
**What are you trying to accomplish?**
Are you trying to deploy the platform for the first time? no
Is this about operating a deployed platform? no
Tell us a bit about what is going on.

Where can we set the budget time range? Currently it is defaulted to monthly. What if we we want to set it to quarterly or yearly?

**Labels**
Please add labels that indicate which component(s) this request is related to.
Modules , data_science module

**Comment by guptamukul-google** [comment]
Hello @speralta-burwood ! Yes currently the billing budgets only support the default budget time range i.e. Month. We will review the request and get back to you with the possibility of supporting custom or other calendar period time ranges in the billing budgets.

**Comment by guptamukul-google** [comment]
@speralta-burwood The feature is now introduced to select the time range in budgets to other than Month. Thank you for sharing your feedback to understand what works and what doesn't work for your client.
