### ISSUE TITLE
Error in gcloud.components.install when running installer_prereq.py on cloud shell

### ISSUE THREAD

**Issue by naclomi** [GoogleCloudPlatform/rad-lab#24]
Hello all!

I was following the quick start instructions to try rad-lab out. Clicking the readme's 'OPEN IN CLOUD SHELL' button opened the shell up and cloned the repo seamlessly. When I ran installer_prereq, though, it exited with the following error (prior successful pip lines omitted to save space):

```
...
Requirement already satisfied: cffi>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from google-crc32c<2.0dev,>=1.0->google-resumable-media<3.0dev,>=1.3.0; python_version >= "3.6"->google-cloud-storage>=1.42.1->-r requirements.txt (line 6)) (1.15.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.0.0->google-crc32c<2.0dev,>=1.0->google-resumable-media<3.0dev,>=1.3.0; python_version >= "3.6"->google-cloud-storage>=1.42.1->-r requirements.txt (line 6)) (2.20)
Installing collected packages: soupsieve, beautifulsoup4, colorama, python-terraform
  Running setup.py install for python-terraform ... done
Successfully installed beautifulsoup4-4.10.0 colorama-0.4.4 python-terraform-0.10.1 soupsieve-2.3.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17.2M  100 17.2M    0     0  86.6M      0 --:--:-- --:--:-- --:--:-- 86.6M
Archive:  terraform_download.zip
  inflating: terraform

Please enter your machine's credentials to complete installation (if requested)...

Detected Cloud Shell, skipping cloud sdk installation...
ERROR: (gcloud.components.install)
You cannot perform this action because the Cloud SDK component manager
is disabled for this installation. You can run the following command
to achieve the same result for this installation:

sudo apt-get install kubectl

PRE-REQ INSTALLTION COMPLETED
```

I tried running the provided apt-get line, but it reported that kubectl was already installed. I'm not sure if this is a fatal error and some stopped further installer steps, or if things will run fine as is. Either way, more clarity in the error message would be helpful :)

**Comment by guptamukul-google** [comment]
Thank you for raising the issue.

It is correct that **kubectl** comes pre-installed in Cloud Shell thus the re-installation is not required. Thus you can continue with triggering the RAD Lab Launcher by running **radlab.py** to deploy modules and things should be fine as is.

Meanwhile we have introduced the quick fix to skip the 'kubectl' installation only when the deployment runs on Cloud Shell to avoid these errors/warnings in future.
