### ISSUE TITLE
document how to use radlab module without an organization

### ISSUE THREAD

**Issue by proppy** [GoogleCloudPlatform/rad-lab#29]
**Is your feature request related to a problem? Please describe.**

I'm trying to use rad-lab with  a personal account, without access to an organization, and it fails on the following line:
https://github.com/GoogleCloudPlatform/rad-lab/blob/1a96f6b71055e62377a3a55c832435358860379b/radlab-launcher/radlab.py#L285

**Describe the solution you'd like**

It would be nice to show how to use the launcher (or even the raw terraform recipe) without an organization.

**Describe alternatives you've considered**

disabling `orgpolicy.tf` seems to mostly do the trick and allow to use `terrform apply` without an empty script as the organization id.

**Comment by guptamukul-google** [comment]
@proppy Thank you for raising this issue. We have introduced an enhancement on RAD Lab Launcher i.e. Spinning up RAD Lab modules via RAD Lab Launcher without an **Organization** and have also updated the RAD Lab Launcher [README](https://github.com/GoogleCloudPlatform/rad-lab/tree/main/radlab-launcher#launch-preparation) accordingly.

Hope this will help other users as well who want to use RAD Lab but have no organization set up. 

Closing this Issue.
