### ISSUE TITLE
distribute module on the terraform registry

### ISSUE THREAD

**Issue by proppy** [GoogleCloudPlatform/rad-lab#30]
**Is your feature request related to a problem? Please describe.**

rad-lab module are not discoverable on:
https://registry.terraform.io/search/providers?q=radlab
https://registry.terraform.io/search/modules?q=google

**Describe the solution you'd like**

it would be nice to be able to find versioned radlab module on https://registry.terraform.io/ with structured documentation about input, output and dependencies.

**Describe alternatives you've considered**

The README.md already provide similar informations https://github.com/GoogleCloudPlatform/rad-lab/tree/main/modules/data_science, but it's not discoverable / visible along side other GCP modules in the terraform registry: https://registry.terraform.io/search/modules?q=google

**Comment by guptamukul-google** [comment]
Hello @proppy !

We are closing out this enhancement with the below Justification:

> We would have to rename the repository in order to do this and the Terraform registry usually is a 1:1 mapping (meaning 1 module - 1 reference in the registry).  Given that ours is a collection of modules, it would be a bit of a challenge to add it there.  I mean, there is nothing wrong to have submodules in your repo, which CFT does as well (as you can see here: https://github.com/terraform-google-modules/terraform-google-project-factory), but they all support the same purpose, while ours are all completely different.  On top of that, they also impose a directory structure and file structure for the top level, which we don't have either (because our submodules don't really support the same purpose).

Here a bit more background: https://www.terraform.io/docs/registry/modules/publish.html

Just this solution will solely be maintained on the GitHub (on this public repo) for now and in near future.
