### ISSUE TITLE
Change how module selection works

### ISSUE THREAD

**Issue by agussman** [GoogleCloudPlatform/rad-lab#7]
In reference to: https://github.com/GoogleCloudPlatform/rad-lab/blob/87c7d768007062cffaa40a851d6b054f5a21150b/scripts/radlab-installer/radlab.py#L55

I have two concerns with the current module selection flow in `radlab.py`.

1) The creation of any additional modules requires editing the script.

2) There's no clear mapping between module directories and what they are named in the script.

This could be addressed by some combination of supplying module name(s) on the command line at launch and/or automatically reading the contents of the `modules` directory and each module should have a standard `name=whatever` which is displayed before the name of the module directory, e.g.:

```
List of available RADLab modules:
[1] Data Science <modules/data_science>
[2] Exit
```

**Comment by guptamukul-google** [comment]
This enhancement is now developed and pushed as part of [RAD Lab v2.1.0 Release]( https://github.com/GoogleCloudPlatform/rad-lab/releases/tag/v2.1.0).

Thank you for raising the enhancement request.
