### ISSUE TITLE
Use STATE_CREATE_XXX Variables

### ISSUE THREAD

**Issue by agussman** [GoogleCloudPlatform/rad-lab#8]
https://github.com/GoogleCloudPlatform/rad-lab/blob/99f1e7f659a98ba22cf45a64052a5bcaf5eae948/radlab-launcher/radlab.py#L289

Assuming these variables correspond to global vars on Line 36, we should be consistent and use them here and throughout the script.

https://github.com/GoogleCloudPlatform/rad-lab/blob/99f1e7f659a98ba22cf45a64052a5bcaf5eae948/radlab-launcher/radlab.py#L36

**Comment by guptamukul-google** [comment]
Thank you for pointing it out. As this is part of the development which is work in progress we are marking the label to `development contribution` and this is now made consistent via [4fc5332](https://github.com/GoogleCloudPlatform/rad-lab/commit/4fc5332526ddc13ec1bc7c55476b491fd59c0bf7)
