### ISSUE TITLE
sa-p-notebook SA roles

### ISSUE THREAD

**Issue by ghsamira** [GoogleCloudPlatform/rad-lab#80]
**Describe the bug**
The deployed data science managed notebook's sa-p-notebook SA does not have "Service Account User" and "Storage Admin" roles, and therefore users can't write to storage and BQ from within the notebook. The first screen shot is the ideal roles for the full functionality. 

**To Reproduce**
Deploy RAD Lab data science managed notebook module in a GCP environment that has +90 security measures ([reference](https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/tree/main/solutions/landing-zone)):

**Expected behavior**
Users should be able to write to Cloud Storage (error message in the logs) and BQ (error in the 2nd screenshot) from within the notebook. 
**Screenshots**
<img width="886" alt="image" src="https://user-images.githubusercontent.com/94209623/193705134-86d6356f-6a40-4f0f-ab69-2a02dd49cc38.png">

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/94209623/193705320-ed1a71c4-853a-49da-a2bd-868884f40871.png">

**Desktop (please complete the following information):**

 - Browser chrome

**Additional context**

**Logs**
PermissionDeniedError: Error executing an HTTP request: HTTP response code 403 with body '{
  "error": {
    "code": 403,
    "message": "sa-p-notebook-0e2b@samiramanagednotebook.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket.",
    "errors": [
      {
        "message": "sa-p-notebook-0e2b@samiramanagednotebook.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket.",
        "domain": "global",
        "reason": "forbidden"
      }
    ]
  }
}
**Labels**
Please add a label that identifies what component(s) this issue applies to.

**Comment by guptamukul-google** [comment]
The fix has been introduced to main branch of the repo. Closing out this issue. Please feel free to reach out if you have any questions or concerns.
