### ISSUE TITLE
Simplify bucket selection flow by prompting for project and then bucket

### ISSUE THREAD

**Issue by agussman** [GoogleCloudPlatform/rad-lab#9]
https://github.com/GoogleCloudPlatform/rad-lab/blob/99f1e7f659a98ba22cf45a64052a5bcaf5eae948/radlab-launcher/radlab.py#L474

I think bucket selection, project selection, and the interplay between the two could be simplified by changing to the following flow:

1) Prompt "Which Project would you like to use for RAD Lab management? (Default: <current set project>)"

2) Prompt "Which Cloud Storage Bucket would you like to use for management? (0 to create new bucket)"

3) List buckets within project and either use the provided number or go down the create bucket flow if they select 0

**Comment by guptamukul-google** [comment]
Currently we already covering **point 1** under [Steps to Install RAD Lab Pre-requisites](https://github.com/GoogleCloudPlatform/rad-lab/tree/99f1e7f659a98ba22cf45a64052a5bcaf5eae948/radlab-launcher#steps-to-install-rad-lab-pre-requisites) in the 
 the _RAD Lab Launcher README.md_ documentation.

> 1. Prompt "Which Project would you like to use for RAD Lab management? (Default: )"


<img width="1081" alt="Screen Shot 2021-11-11 at 9 37 42 PM" src="https://user-images.githubusercontent.com/9626165/141415694-f54f4bcb-d28b-4120-8f5c-ac835c8f5e1e.png">

We are already doing below 2 steps as part of RAD Lab Launcher.
> 2. Prompt "Which Cloud Storage Bucket would you like to use for management? (0 to create new bucket)"
> 3. List buckets within project and either use the provided number or go down the create bucket flow if they select 0

I am marking this as `enhancement` to be considered in future releases.

**Comment by guptamukul-google** [comment]
As part of this enhancement, RAD Lab Launcher now prompts for Project ID for RAD Lab management. This will provide more visibility and simplify overall RAD Lab management. Creation / Utilization of GCS bucket (where Terraform states will be stored) will be done within the project selected as per this enhancement.

Closing this request.
