### ISSUE TITLE
Default region/zone for RAD Lab UI is not stored correctly and not used correctly

### ISSUE THREAD

**Issue by debakkerb** [GoogleCloudPlatform/rad-lab#96]
**Describe the bug**
When installing the RAD Lab UI, one of the first steps as an Admin is to configure default region and zone.  However, the values are not persisted correctly in the Firestore database. 

**To Reproduce**
In the RAD Lab UI:
1. Go to `Setup`
2. Click `Next` until you arrive at step 4 where you provide `region`/`zone`
3. Update to a non-US `region` and `zone` (`europe-west1` and `europe-west1-b` in my scenario)

**Expected behavior**
In Firestore, the values should have been updated to `europe-west1` and `europe-west1-b`.  However, it shows `europe-west1` as region and `us-central1-a` as zone

**Comment by acolver** [comment]
Fixed with https://github.com/GoogleCloudPlatform/rad-lab/pull/170
