### ISSUE TITLE
Default region/zone in Rad Lab UI not taken into account

### ISSUE THREAD

**Issue by debakkerb** [GoogleCloudPlatform/rad-lab#97]
**Describe the bug**
As an Admin, you can run through the Setup flow to configure default values for a number of variables (`organization`, `folder`, ...).  During this wizard, you can also configure a default value for `region` and `zone`.  However, when running through a deployment, it still uses the default values that are set in `variables.tf`, as opposed to using the ones stored in Firestore.

**To Reproduce**
1. Open Rad Lab UI and login as Admin
2. Go to `Setup` and click Next until you arrive at page 4 to configure the default `region` and `zone`
3. Update to a non-US region and zone (in my case, it was `europe-west1` and `europe-west1-b`.
4. Save
5. Click on `Deploy`
6. Deploy `data_science` module
7. Click `Next`

**Expected behavior**
On the second page, it shows a listbox for `zone`.  This contains the value set in `variables.tf` and not the zone configured as a default in Firestore.

**Comment by acolver** [comment]
Let me broaden this to how we handle variables in general (if the general case is fixed it will also fix this specific issue)

Variable priority should be as follows (with #1 being top priority):
1. User provided variables (this excludes group=0 variables as users cannot set them)
2. Modules variables
3. Global Admin variables
4. Defaults in `variables.tf`

Values may be set an all, some, or none of these levels. When there are some/all values for a given variable, we should show in the UI and submit to the Cloud Build job only the top priority variable value.

**Comment by acolver** [comment]
@guptamukul-google We need to figure out a way to make
1. Make the region/zone options pull from the full list (when they are listed as a TFVar) Ex: https://github.com/GoogleCloudPlatform/rad-lab/blob/main/modules/data_science/variables.tf#L283
2. We need to merge in the admin settings (as mentioned in my previous comment)

**Comment by acolver** [comment]
Fixed with https://github.com/GoogleCloudPlatform/rad-lab/pull/170
